name: CI-CD

on:
  push:
    branches:
      - main

env:
  CONTAINER: ${{ github.event.repository.name }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract Docker metadata
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.CONTAINER }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image to the Docker Hub
        uses: docker/build-push-action@v5
        with:
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.CONTAINER }}:latest
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Deploy to Server via SSH action
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: CONTAINER
          script: |
            # Login into Docker Hub
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            
            # Stop running container
            docker stop $(echo $CONTAINER)
            
            # Remove old container
            docker rm $(echo $CONTAINER)
            
            # Remove old image
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/$(echo $CONTAINER)
            
            # Set env variables
            export PORT=${{ secrets.PORT }}
            
            # Run a new container from a new image
            docker run -e PORT -d \
            --restart always --net internal \
            --publish ${{ secrets.PORT }}:${{ secrets.PORT }} \
            --name $(echo $CONTAINER) \
            ${{ secrets.DOCKERHUB_USERNAME }}/$(echo $CONTAINER):latest
